coverage:
  notify:
    slack:
      default:
        url: "https://hooks.slack.com/services/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"
        only_pulls: false
        branches: 
          - "main"
        paths: 
          - "src"
